config/routes.rb
Rails.application.routes.draw do
  get 'how_to', to: 'home#how_to'
  get 'privacy', to: 'home#privacy'
  devise_for :users
  resources :quests do
     resources :messages do
       post 'payout'
     end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :quest
  belongs_to :user, optional: true

  validates_length_of :text, :minimum => 2, :maximum => 3000
  validate :valid_iota_address

  require 'iota'

  def valid_iota_address
    utils = IOTA::Utils::InputValidator.new
    errors.add(:address, "Not a valid iota address.") unless utils.isAddress(address)
    pp errors.to_json
  end

end

app/models/quest.rb
class Quest < ApplicationRecord

  enum status: [:active, :payout_proccessed, :inactive]

  before_create :create_address
  require 'iota'

  has_many :messages
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]
  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, :slug, presence: true
  validates :title, length: { minimum: 5, maximum: 81 }
  validates :description, length: { minimum: 5, maximum: 3000 }

  def create_address
    # Create client directly with provider
    client = IOTA::Client.new(provider: 'https://iota.nodes24.com')

    # now you can start using all of the functions
    status, data = client.api.getNodeInfo

    ## create and save seed
    self.seed = (1..81).map{'ABCDEFGHIJKLMNOPQRSTUVWXYZ9'[SecureRandom.random_number(27)]}.join('')

    ## create and save latest address
    account = IOTA::Models::Account.new(client, self.seed)
    account.getAccountDetails({})

    self.latest_address = account.latestAddress
    self.status = :active

  end

  def solver
    solver_id == 0 ? 'anonymous' : User.find(solver_id).name
  end

  def solution
    solution_id == 0 ? nil : messages.find(solution_id)
  end

  def payout message

    utils = IOTA::Utils::InputValidator.new
    return false unless utils.isAddress(message.address)


    self.solver_id = message.user.id if message.user
    self.solution_id = message.id
    SolutionPayoutJob.perform_later(self, message)
    self.payout_proccessed!

   return true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
        :lockable, :confirmable, :trackable

  has_many :quests

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]
  def should_generate_new_friendly_id?
    name_changed?
  end

  validates :name, :slug, presence: true
  validates :name, uniqueness: true, length: { minimum: 1, maximum: 100 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def permission_denied
    redirect_to root_url, notice: 'Permission denied!'
  end

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def how_to
  end
  def privacy
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: :create

  before_action :set_quest

  def create
    @message = Message.new(message_params)
    @message.quest = @quest
    @message.user = current_user if params[:user] == "true"

    if @message.save
      redirect_to @quest, notice: 'Message was successfully created.'
    else
      render "quests/show"
    end
  end

  def index
    @message = Message.new
    render "quests/show"
  end

  def payout
    return permission_denied unless current_user == @quest.user
    message = @quest.messages.find(params[:message_id])
    respond_to do |format|
      if @quest.payout(message)
        format.html { redirect_to @quest, notice: 'Payout was a success.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { redirect_to @quest, notice: 'Something went wrong!' }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_quest
    @quest = Quest.find(params[:quest_id])
  end

  def message_params
    params.require(:message).permit(:text, :address)
  end

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all.where(status: :active)
    @sovled_quests = Quest.all.where(status: :inactive).order(payed_at: :asc)
    @hero_quest = @quests.sample
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
    @messages = @quest.messages
    @message = Message.new
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = current_user.quests.new(quest_params)
    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    return permission_denied unless current_user == @quest.user
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    return permission_denied unless current_user == @quest.user
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:title, :description, messages_attributes: [:id, :text, :address, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/home/_hero_animation.html.erb
<div class="particles">

</div>
<% quest = Quest.new unless quest %>
<div class="animation-wrapper">
  <div class="animation-container">
    <div class="circle-wrapper">
      <%= image_tag "hero/circle/circle-path_1.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_2.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_3.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_4.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_5.svg", class:"circle-outline size-md" %>
      <%= image_tag "hero/circle/circle-path_6.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_7.svg", class:"circle-outline transparent-20 size-sm" %>
      <%= image_tag "hero/circle/circle-path_8.svg", class:"circle-outline size-md" %>
      <%= image_tag "hero/circle/circle-path_9.svg", class:"circle-outline size-lg" %>
      <%= image_tag "hero/circle/circle-path_10.svg", class:"circle-outline transparent-20 size-sm" %>
      <%= image_tag "hero/circle/circle-path_11.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_12.svg", class:"circle-outline size-lg" %>
      <%= image_tag "hero/circle/circle-path_13.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_14.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_15.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_16.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle-dots.svg", class:'circle-dots-1' %>
      <%= image_tag "hero/circle-dots.svg", class:'circle-dots-2' %>
      <div class="inner-circle">
        <div class="circled-quest">
          <div class="circled-quest-body">
            <% if quest.id %>
              <h3><%= quest.user&.name %></h3>
              <p><%= quest.title %></p>
              <div class="circled-quest-body__footer">
                <div class="footer-button">
                  <%= image_tag "message.svg" %>
                  <span><%= quest.messages.count %></span>
                </div>
              </div>
              <%= link_to quest_path(quest), class: 'play-btn' do %>
                <span>Play now</span>
              <% end %>
            <% else %>
            <%= image_tag 'logo_white.svg', style: 'opacity: 1; width: 200px;' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="portal-wrapper">
      <%= image_tag "hero/portal2.svg" %>
      <div class="circle-lines-wrapper">
        <%= image_tag "hero/circle-lines-final.svg", class: 'circle-lines', style: 'opacity: .5;' %>
      </div>
      <div class="iota-logo-wrapper">
        <%= image_tag "iota.svg", class: 'iota-logo' %>
      </div>
    </div>
  </div>
</div>

app/views/home/how_to.html.erb
<% content_for :title, "Quests - How to..." %>

<div class="section section--hero small">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Help</h1>
      </div>
    </div>
  </div>
  <div class="particles">

  </div>
</div>
<div class="section section--index">
  <div class="container">
    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-8">
        <h3>How to solve a quest?</h3>
        <div class="text-element content-element circles-list">
          <ol>
            <li>Find a quest that you can solve.</li>
            <li>Suggest a solution, add your IOTA address.</li>
            <li>If the quest creator accepts your solution, you will get the donations.</li>
          </ol>
        </div>

        <h3>How to create a quest?</h3>
        <div class="text-element content-element circles-list">
          <ol>
            <li><%= link_to "Sign In", new_user_session_path %>, or <%= link_to "create an account", new_user_registration_path %>.</li>
            <li>Go to <%= link_to "create a quest", new_quest_url %> - Set a quest title and describe your quest then create it.</li>
            <li>Send some IOTA's to the quest address.</li>
            <li>Share the quest link with your people and wait for some solutions.</li>
            <li>Payout the solution, which you like the most - and support the one that helped you most.</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 footer-wrapper">
        <a href="/">
          <%= image_tag "logo_white.svg", class: 'footer-logo' %>
        </a>
        <div class="footer-slogan">
          <span>Made with </span>
          <%= image_tag "love.svg" %>
          <span>and </span>
          <a href="https://www.iota.org" target="_blank"><%= image_tag "iota.svg" %></a>
          <span> by <a href="https://ecosystem.iota.org/users/huhn" target="_blank">huhn</a> and <a href="https://ecosystem.iota.org/users/rep0x" target="_blank">r3p0x</a></span>
        </div>
        <div class="sm-links">
          <a href="#">
            <%#= image_tag "twitter.svg" %>
          </a>
          <a href="#">
            <%#= image_tag "discord.svg" %>
          </a>
          <a href="#">
            <%#= image_tag "gitlab.svg" %>
          </a>
        </div>
        <a href="<%= privacy_path %>" class="footer-privacy">Privacy Policy</a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag("logo_white.svg") %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <div class="navbar-toggler-wrapper">
      <span class="line line__top"></span>
      <span class="line line__center"></span>
      <span class="line line__bottom"></span>
    </div>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= "active" if request.path == '/' %>">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item <%= "active" if request.path == '/how_to' %>">
        <a class="nav-link" href="/how_to">Help</a>
      </li>
      <li class="nav-item nav-item--btn">
        <%= link_to 'Create a quest', new_quest_path, class: 'btn btn-primary nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'application/favicon' %>
    <meta name=”description” content=”Quests is the worlds first platform where you can earn IOTA for solving issues all around the world. No traveling. No contracts. Not even a sign-up. Just do it!” />
    <meta property=”og:title” content=”<%= yield(:title) %>” />
    <meta property=”og:description” content=”Quests is the worlds first platform where you can earn IOTA for solving issues all around the world. No traveling. No contracts. Not even a sign-up. Just do it!” />
    <meta property=”og:url” content=”http://quests.worldofmind.org/" />
    <meta property=”og:image” content=”http://quests.worldofmind.org/<%= image_path "logo.svg" %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="notice alert alert-bottom" role="alert">
      <strong>Beta!</strong> This software is currently in a beta phase. We assume no liability. If you need help or have questions, feel free to leave a message to <a href="mailto:quests@worldofmind.org">quests@worldofmind.org</a>. Thanks!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% if notice %>
      <div class="notice alert alert-primary alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>Notice: </strong> <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>Alert: </strong> <%= alert %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message_fields.html.erb
<%= form_for message, url: {controller: 'messages', action: "create", quest_id: quest.id, anchor: 'new_message'}, html: {class: ""} do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this solution from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="card">
     <div class="card-body">
       <h3 class="card-title">Your solution</h3>
       <p class="card-text">
        <div class="field">
          <%= form.label :text, "description" %>
          <%= form.hidden_field :text %>
          <trix-editor input="message_text" placeholder="Lorem ipsum dolor sit amet..."></trix-editor>
        </div>

        <div class="field" data_type="iota">
          <%= form.label :address %>
          <%= form.text_field :address, class: "form-control", placeholder: "Your IOTA address. E.g. 'ADKLWNGMRLE9AD...'" %>
        </div>

        <div class="field">
          <%= form.label "post as" %>
          <% if current_user %>
            <%= select_tag "user", options_for_select([["as #{current_user.name}", 'true'], ['anonymous', 'false']]), class: "form-control" %>
          <% else %>
            <p>anonymous, or <%= link_to "create an account", new_user_registration_path %></p>
          <% end %>
        </div>

        <div class="actions" style="margin-bottom: 0;">
          <%= form.submit "Post", class: "btn btn-primary form-control" %>
        </div>
     </div>
   </div>

 <% end %>

app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>
      <ul>
      <% quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" data_type="title">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: 'My awesome quest', autofocus: true %>
  </div>

  <div class="field" data_type="text">
    <%= form.label :description %>
    <%= form.hidden_field :description, class: "form-control" %>
    <trix-editor input="quest_description" placeholder="Enter a detailed description of your quest. Try to define what people need to do in order to solve the quest." ></trix-editor>
  </div>

  <div class="form-actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/quests/edit.html.erb
<% content_for :title, "Quests - Edit your quest!" %>

<div class="section section--hero small">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Edit Quest</h1>
      </div>
    </div>
  </div>
  <div class="particles"></div>
</div>
<div class="section section--index">
  <div class="container">
    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-8">
        <%= render 'form', quest: @quest %>
        <div class="form-actions">
          <%= link_to 'Back', quests_path, class: 'btn btn-dark' %> |
          <%= link_to 'Show', @quest, class: 'btn btn-dark' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quests/index.html.erb
<% content_for :title, "Quests" %>

<div class="section section--hero" style="padding-top: 0;">
  <div class="container container--hero">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h1>Stop working. Start playing.</h1>
        <h5>Find a quest. Solve it.</h5>
        <p>Quests is the worlds first platform where you can earn IOTA for solving issues all around the world.
           No traveling. No contracts. Not even a sign-up. Just do it!</p>
         <div class="btn-wrapper">
           <a class="btn btn-primary btn-lg" href="/how_to" role="button">Learn more</a>
           <a class="btn btn-primary btn-lg" href="<%= new_quest_path %>" role="button">Create a quest</a>
         </div>
         <div class="kpi-wrapper">
           <div class="kpi-box" data-id="tab-open-quests">
             <h2><%= @quests.count %></h2>
             <h6>Open Quests</h6>
           </div>
           <div class="kpi-box" data-id="tab-solved-quests">
             <h2><%= @sovled_quests.count %></h2>
             <h6>Solved Quests</h6>
           </div>
         </div>
      </div>
    </div>
  </div>
  <%= render "home/hero_animation", quest: @hero_quest %>
</div>
<div class="section section--index">
  <div class="container">
    <div class="row" style="margin-bottom: 30px;">
      <div class="col-sm-12">
        <h2 style="text-align: center;">Quests</h2>
        <p style="max-width: 600px; text-align: center; margin: 0 auto;">Find a quest that you can solve. Solve it and earn IOTA if you suggested the best solution.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <nav class="nav nav-pills nav-justified">
          <a  id="tab-open-quests-tab" class="nav-item nav-link tablinks active" onclick="openTab(event, 'tab-open-quests')">Open Quests</a>
          <a  id="tab-solved-quests-tab" class="nav-item nav-link tablinks" onclick="openTab(event, 'tab-solved-quests')">Solved Quests</a>
        </nav>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 quest-list-container tabcontent" id="tab-open-quests">
        <% @quests.each do |quest| %>
          <a href="<%= quest_path(quest) %>" class="quest-item">
            <div class="quest-item__body">
              <div class="quest-item__header">
                <span style="opacity: .5;">Created by <%= quest.user.name %>, <%= time_ago_in_words quest.created_at %> ago</span>
              </div>
              <h6><%= quest.title %></h6>
            </div>
            <div class="quest-item__footer">
              <div class="footer-button">
                <%= image_tag "message.svg" %>
                <span><%= quest.messages.count %> suggestions</span>
              </div>
            </div>
          </a>
        <% end %>
      </div>
      <div class="col-sm-12 quest-list-container tabcontent" style="display: none;" id="tab-solved-quests">
        <% @sovled_quests.each do |quest| %>
          <a href="<%= quest_path(quest) %>" class="quest-item">
            <div class="quest-item__body">
              <div class="quest-item__header">
                <span style="opacity: .5;">Created by <%= quest.user.name %>, <%= time_ago_in_words quest.created_at %> ago</span>
                <span style="opacity: .5;">Solved by <%= quest.solver %>, <%= quest.payed_at ? "#{time_ago_in_words(quest.payed_at)}" : "on release date"  %> ago.</span>
              </div>
              <h6><%= quest.title %></h6>
            </div>
            <div class="quest-item__footer">
              <div class="footer-button">
                <%= image_tag "message.svg" %>
                <span><%= quest.messages.count %></span>
              </div>
              <div class="footer-button">
                <%= image_tag "iota.svg" %>
                <span><%= quest.payed_amount if quest.payed_amount %></span>
              </div>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quests/new.html.erb
<% content_for :title, "Quests - Create your quest!" %>

<div class="section section--hero small">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>New Quest</h1>
      </div>
    </div>
  </div>
  <div class="particles"></div>
</div>
<div class="section section--index">
  <div class="container">
    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-8">
        <%= render 'form', quest: @quest %>
        <div class="form-actions">
          <%= link_to 'Back', quests_path, class: 'btn btn-dark' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quests/show.html.erb
<% content_for :title, "Quests -  #{ @quest.title}" %>
<% if @quest.inactive? %>
  <div class="alert alert-warning" role="alert">
    <strong>Closed!</strong> This quest is completed!
  </div>
<% elsif @quest.payout_proccessed? %>
<div class="alert alert-warning" role="alert">
  <strong>Closed!</strong> This payout is processig!
</div>
<% end %>
<div class="section section--hero small">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 back-title">
        <h1><%= @quest.title %></h1>
      </div>
    </div>
  </div>
  <div class="particles"></div>
</div>
<div class="section section--index">
  <div class="container">
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8 quest-details">
        <div class="jumbotron">
          <div class="options-wrapper options-wrapper__left">
            <%= link_to 'Back', quests_path, class: 'btn btn-dark', style: 'margin-right: 15px;' %>
          </div>
          <div class="options-wrapper">
            <%= link_to 'Edit', edit_quest_path(@quest), id:'edit-btn', class: 'btn btn-dark' if current_user&.id == @quest.user_id  %>
          </div>
          <div class="quest-description"><%= sanitize @quest.description %></div>
          <p style="opacity: .5;">Created by <%= @quest.user.name %>, <%= time_ago_in_words @quest.created_at %> ago</p>
          <div class="react-balance">
            <%= react_component("Balance", { address: @quest.latest_address }) if @quest.active? %>
            <div class="balance-footer">
              <% if @quest.active? %>
                <div class="buttonCopyAddressk" data-toggle="tooltip" data-placement="bottom" title="<%= @quest.latest_address %>"  data-address="<%= @quest.latest_address %>">
                  <%= @quest.latest_address.truncate(9, omission: "...#{@quest.latest_address.last(3)}") %>
                </div>
                <button type="button" class="btn btn-primary buttonCopyAddressk" style="margin-bottom: 10px;" data-address="<%= @quest.latest_address %>">Copy address</button>
              <% elsif @quest.payout_proccessed? %>
              <p>Payout is done soon...</p>
              <% else %>
              <p>Payed out <%= time_ago_in_words @quest.payed_at  %> ago to  <%= link_to "solution", quest_path(@quest, anchor: "solution-#{@quest.messages.find_index(@quest.solution) + 1}") %></p>
              <% end %>
              <%= link_to "Check on TheTangle.org", "https://www.thetangle.org/address/#{@quest.latest_address}", target: '_blank' %>
            </div>
          </div>
        </div>
        <h2>Suggested solutions</h2>
        <% @quest.messages.each_with_index do |message, index| %>
          <div id="solution-<%= index + 1 %>" class="card <%= "text-white bg-success" if message == @quest.solution %>">
            <div class="options-wrapper options-wrapper__small">
              <% if @quest.active? && current_user&.id == @quest.user_id %>
                <%= button_to "Payout", quest_message_payout_path(@quest, message), class: 'btn btn-primary btn-xs' %>
              <% end %>
              <button type="button" class="btn btn-dark btn-xs buttoncopySolutionLink" style="margin-left: 15px;">Copy Solution Link</button>
            </div>
            <div class="card-body">
              <h3>Solution #<%= index + 1 %> </h3>
              <p class="card-text"><%=sanitize message.text %></p>
              <p style="opacity: .5; margin-bottom: 0;">Posted by <%= message.user ? message.user.name : 'anonymous' %>, <%= time_ago_in_words message.created_at  %> ago</p>

              <% if @quest.active? && current_user&.id == @quest.user_id %>
              <% elsif message == @quest.solution && !@quest.payout_proccessed? %>
                <br>
                <p>Payed out <%= @quest.payed_amount ? @quest.payed_amount : "unknown" %> IOTA <%= time_ago_in_words @quest.payed_at  %> ago.</p>
                <a href="https://www.thetangle.org/address/<%= @quest.solution.address %>" target="_blank">Watch payment on TheTangle.org</a>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= render 'messages/message_fields', message: @message, quest: @quest if @quest.active? || @quest.payout_proccessed? %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>